import type { Metadata } from 'next';
import '../styles/globals.css';
import React from 'react';
import { CartProvider } from '@/contexts/CartContext';
import ConfirmDeleteModal from '@/components/ConfirmDeleteModal';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body>
        <CartProvider>
          {children}
          <ConfirmDeleteModal />
        </CartProvider>
      </body>
    </html>
  );
}
